### ISSUE TITLE
Update - JS & CSS

### ISSUE THREAD

**Issue by w3sanju** [w3sanju/hello-world#1]
Update script.js

``` javascript
if (isFunction){
      return true
    }
```

Update style.css

``` css
body{color:#fff;}
```
